[project]
name = "mapbox-generator"
version = "0.1.0"
description = "Generate beautiful static route maps with Mapbox Static Images API, perfect for banners, flyers, or web use."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.1.0",
    "requests>=2.32.4",
]
